// Words grouped by length for progressive difficulty.
// All lowercase — display layer handles uppercase.

const kWordList = [
  // 3–4 letters
  'bit', 'bus', 'cpu', 'hex', 'ram', 'run', 'key', 'map', 'net',
  'log', 'bug', 'fix', 'add', 'set', 'pop', 'cat', 'dog', 'sun',
  'sea', 'sky', 'ice', 'art', 'war', 'joy', 'code', 'data', 'file',
  'flag', 'fork', 'hash', 'list', 'loop', 'node', 'null', 'port',
  'root', 'sort', 'swap', 'tree', 'type', 'void', 'byte', 'base',
  'fire', 'wind', 'rain', 'snow', 'bird', 'fish', 'star', 'moon',
  'wave', 'cave', 'road', 'gate', 'mine', 'rock', 'leaf', 'seed',
  'time', 'life', 'word', 'book', 'hand', 'mind', 'line', 'flow',
  'grid', 'plan', 'mark', 'link', 'lock', 'path', 'step', 'wall',
  'call', 'pass', 'read', 'draw', 'jump', 'drop', 'grow', 'move',
  'play', 'stay', 'turn', 'open', 'send', 'find', 'keep', 'show',
  'land', 'sand', 'hill', 'lake', 'dawn', 'dusk', 'mist', 'gust',
  'gold', 'iron', 'lead', 'rust', 'dust', 'foam', 'glow', 'beam',
  'text', 'font', 'icon', 'menu', 'form', 'card', 'chat', 'mail',

  // 5–7 letters
  'array', 'cache', 'class', 'queue', 'stack', 'tuple', 'yield',
  'debug', 'error', 'proxy', 'query', 'regex', 'token', 'patch',
  'pixel', 'frame', 'scene', 'tiger', 'eagle', 'river', 'ocean',
  'storm', 'stone', 'light', 'night', 'music', 'dance', 'dream',
  'world', 'north', 'south', 'green', 'black', 'white', 'brave',
  'swift', 'sharp', 'quiet', 'magic', 'lucky', 'happy', 'proud',
  'binary', 'buffer', 'cursor', 'daemon', 'decode', 'encode',
  'kernel', 'memory', 'module', 'packet', 'parser', 'output',
  'signal', 'socket', 'syntax', 'vector', 'thread', 'server',
  'forest', 'bridge', 'castle', 'flower', 'mirror', 'planet',
  'silver', 'shadow', 'winter', 'autumn', 'spring', 'summer',
  'friend', 'family', 'legend', 'travel', 'harbor', 'beacon',
  'index', 'watch', 'fetch', 'build', 'chunk', 'block', 'batch',
  'house', 'table', 'chair', 'glass', 'clock', 'bread', 'water',
  'earth', 'cloud', 'heart', 'brain', 'smile', 'power', 'space',
  'floor', 'voice', 'level', 'track', 'field', 'speed', 'clear',
  'solid', 'place', 'story', 'angle', 'focus', 'cycle', 'range',
  'point', 'graph', 'value', 'model', 'state', 'phase', 'cross',
  'depth', 'width', 'brush', 'layer', 'blend', 'draft',
  'scout', 'forge', 'craft', 'tower', 'ridge', 'coast', 'marsh',
  'grove', 'blaze', 'frost', 'flare', 'ember', 'spark', 'surge',
  'drift', 'shift', 'climb', 'trace', 'bound', 'pulse', 'burst',
  'prism', 'nexus', 'relay', 'scope', 'probe', 'alias',
  'quote', 'epoch', 'delta', 'alpha', 'gamma', 'omega', 'sigma',

  // 8–10 letters
  'compiler', 'database', 'debugger', 'function', 'instance',
  'iterator', 'keyboard', 'listener', 'markdown', 'overflow',
  'pipeline', 'platform', 'register', 'renderer', 'selector',
  'template', 'terminal', 'variable', 'callback', 'argument',
  'document', 'password', 'mountain', 'together', 'champion',
  'treasure', 'panorama', 'calendar', 'absolute', 'creative',
  'fragment', 'gradient', 'northern', 'southern', 'thousand',
  'universe', 'wildfire', 'sunlight', 'midnight', 'symphony',
  'internet', 'airplane', 'notebook', 'blackout', 'feedback',
  'algorithm', 'framework', 'interface', 'parameter', 'recursion',
  'exception', 'prototype', 'singleton', 'debugging', 'namespace',
  'benchmark', 'clipboard', 'directory', 'multicast', 'operation',
  'language', 'standard', 'building', 'question', 'software',
  'response', 'snapshot', 'launcher', 'shortcut', 'dropdown',
  'viewport', 'timeline', 'workflow', 'network', 'redirect',
  'manifest', 'checksum', 'baseline', 'rollback', 'scaffold',
  'observer', 'provider', 'consumer', 'composer', 'resolver',
  'adventure', 'discovery', 'community', 'wonderful', 'beautiful',
  'chocolate', 'hurricane', 'telescope', 'orchestra', 'cathedral',
  'labyrinth', 'starlight', 'celestial', 'equilibrium', 'lightning',
  'sandstorm', 'daybreak', 'downfall', 'upstairs', 'tomorrow', 'children',
  'electron', 'hydrogen', 'nitrogen', 'spectrum', 'magnetic',
  'velocity', 'momentum', 'particle', 'reaction', 'equation',
];
